services:
  identigraf:
    build:
      context: .docker/identigraf
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - NO_UPDATE_NOTIFIER=true
      - NPM_CONFIG_FUND=0
      - SUPPRESS_SUPPORT=1
      - HTTPS=0
      - PORT=3000
      - ENABLE_TRACING=1
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - HAVE_SWAGGER=true
      - FACEX_URL
      - npm_config_userconfig=/usr/src/service/.npmrc.local
    restart: always
    volumes:
      - "../:/usr/src/service"
    working_dir: /usr/src/service

  zipkin:
    image: openzipkin/zipkin:latest@sha256:5fd55e6a109233b36d419d7fd2449588d17a6e4da7ed7a3fd0d09c86f1c75a15
    restart: always

  swagger:
    image: swaggerapi/swagger-ui:latest@sha256:c17153d23b81490d9b1d56bb26448b44b2fd43e46e8656ccb6af34eceb291a79
    environment:
      - SWAGGER_JSON_URL=/specs/identigraf-private.yaml
      - BASE_URL=/swagger
